# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  /home/wisig/Videos/gokul/coco_tb/my_design.sv
vsim  -onfinish exit -pli /home/wisig/Videos/gokul/coco_tb/cocotb-venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   work.my_design
onbreak resume
run -all
quit
